### ISSUE TITLE
Possible typo in ppd/ppd-ipp.c?

### ISSUE THREAD

**Issue by zdohnal** [OpenPrinting/libppd#36]
The code line [here](https://github.com/OpenPrinting/libppd/blob/24839b5cb49c2e1392f0b91f0af8d2c6529f074b/ppd/ppd-ipp.c#L661C43-L661C43) looks like a typo - everything multiplied by zero is zero.

**Comment by tillkamppeter** [comment]
This piece of code is to determine whether the string `items[0]` is an integer number or not. First it is checked whether it is not empty and if so, the function `strtol()` is applied. The `* 0` we do as we want to ignore the actual number discovered. This makes the left hand side of the `||` always false so that we evaluate the right hand side. Here we check whether `strtol()` errorred and whether it interpreted the whole string as a number. If there is no error and the whole string was interpreted as number, `item[0]` is considered a number.
```
      else if (strlen(items[0]) > 0 &&
	       ((int)(strtol(items[0], &p, 10) * 0) ||
		(errno == 0 && *p == '\0')))
```
This is exactly as it was designed. I do not remember to have done this, most probably this code stems froma contributor but it is correct.

Closing ...

**Comment by tillkamppeter** [comment]
A simpler solution to achieve the same thing is naturally welcome ...

**Comment by zdohnal** [comment]
Attempt at #38 .
